########################################
# Shell
########################################
config/zsh/zshrc|~/.zshrc

########################################
# Git
########################################
config/git/gitconfig|~/.gitconfig
config/git/gitconfig-agetic|~/.gitconfig-agetic
config/git/gitconfig-personal|~/.gitconfig-personal
config/git/gitconfig-powerfinancial|~/.gitconfig-powerfinancial

########################################
# SSH
########################################
config/ssh/config|~/.ssh/config

########################################
# tmux
########################################
config/tmux/tmux.conf|~/.tmux.conf

########################################
# Starship
########################################
config/starship/starship.toml|~/.config/starship.toml

########################################
# Ghostty
########################################
config/ghostty/config|~/.config/ghostty/config

########################################
# LazyGit
########################################
config/lazygit/config.yml|~/.config/lazygit/config.yml