export DOTFILES="$HOME/Projects/personal/dotfiles"
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# ----------------------------
# Oh My Zsh
# ----------------------------

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-nvm
)

source "$ZSH/oh-my-zsh.sh"

# ----------------------------
# Node (NVM)
# ----------------------------

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && source "$NVM_DIR/bash_completion"

# ----------------------------
# Prompt
# ----------------------------

eval "$(starship init zsh)"

# ----------------------------
# Tools
# ----------------------------

eval "$(zoxide init zsh)"

source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh

export FZF_DEFAULT_OPTS="
--height=40%
--layout=reverse
--border
--info=inline
"

# ----------------------------
# Custom configuration
# ----------------------------

source "$HOME/Projects/personal/dotfiles/config/zsh/aliases.zsh"
source "$HOME/Projects/personal/dotfiles/config/zsh/functions.zsh"

source "$DOTFILES/config/zsh/aliases.zsh"
source "$DOTFILES/config/zsh/functions.zsh"
