##### General #####

# Mouse
set -g mouse on

# Mucho historial
set -g history-limit 100000

# Ventanas desde 1
set -g base-index 1
setw -g pane-base-index 1

# Renumerar automáticamente
set -g renumber-windows on

# Modo copia estilo Vim
setw -g mode-keys vi

# Menor retardo de Escape
set -sg escape-time 10

# Mejor soporte de colores
set -g default-terminal "tmux-256color"

##### Portapapeles #####

# Permite copiar al portapapeles del sistema
set -s set-clipboard on

##### Abrir siempre en el directorio actual #####

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

##### Recargar configuración #####

bind r source-file ~/.tmux.conf \; display-message "tmux.conf recargado"

##### Plugins #####

set -g @plugin 'tmux-plugins/tpm'

# Tema
set -g @plugin 'dracula/tmux'

# Plugins recomendados
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

##### Dracula #####

# Mostrar módulos
set -g @dracula-show-left-icon session
set -g @dracula-show-flags true

set -g @dracula-plugins "cpu-usage ram-usage battery time"

# Formato de la hora
set -g @dracula-time-format "%d/%m %H:%M"

# Mostrar batería
set -g @dracula-show-battery true

# Mostrar CPU
set -g @dracula-show-cpu true

# Mostrar RAM
set -g @dracula-show-ram true

run '~/.tmux/plugins/tpm/tpm'
